# Generated by Django 3.2.4 on 2026-09-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20260906_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='blog\\defalt.jpg', upload_to='blog/'),
        ),
    ]
